---
- name: Installs R1soft Agent 
  become: yes
  become_method: sudo
  user: centos 
  hosts: all 
  tasks:

  - name: Craetes a repo
    when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "6")
    copy: 
      src: r1soft.repo
      dest: /etc/yum.repos.d/r1soft.repo

  - name: Install agent
    when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "6")
    package:
      name: serverbackup-enterprise-agent
      state: present 

  - name: Start agent
    when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "6")
    service:
      name: cdp-agent
      state: restarted 
      enabled: yes

  - name: Stop Iptables
    when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "6")
    service:
      name: iptables
      state: stopped
      enabled: no

  - name: Get key
    when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "6")
    command: "r1soft-setup --get-key http://3.10.57.254:8080/"

